import atriumDining from '../images/atrium-dining.jpg'
import kormangala from '../images/kormangalaa.jpg'
import bandraWest from '../images/bandra-west.jpg'
import bandra from '../images/bandraa.avif'
import caunaught from '../images/caunaught-palace.jpg'
import chicHeaven from '../images/chic-heaven.jpg'
import dwarka from '../images/dwarkaa.jpg'
import greenLounge from '../images/green-lounge.jpg'
import hauz from '../images/hauz-khas.jpg'
import indranagar from '../images/indranagarr.jpg'
import jayanagar from '../images/jayanagar.jpg'
import juhu from '../images/juhuu.jpg'
import mgRoad from '../images/mg-road.jpg'
import panaji from '../images/panajii.jpg'
import parkStreet from '../images/park-street.jpg'
import retroCheck from '../images/retro-check.jpg'
import saltLake from '../images/salt-lake.jpg'
import southExtension from '../images/south-extension.jpg'
import tNagar from '../images/t-nagar.jpg'
import vasant from '../images/vasant-bihar.jpg'
import vile from '../images/vile-parle.jpg'
import sector14 from '../images/sector-14.jpg'
import redWallLounge from '../images/red-wall-lounge.jpg'
import andheriWest from '../images/andheri-west.jpg'
import banjaraHills from '../images/banjara-hills.jpg'
import checkeredCafe from '../images/checkered-cafe.jpg'
import chandniChowk from '../images/chandni-chowk.jpg'
import annaNagar from '../images/anna-nagar.jpg'
import classicWood from '../images/classic-wood.jpg'
import gardenAtrium from '../images/garden-atrium.jpg'
import loftyRetreat from '../images/lofty-retreat.jpg'
import rusticGlowLounge from '../images/rustic-glow-lounge.jpg'
import redRetroLounge from '../images/red-retro-lounge.jpg'
import terraceLounge from '../images/terrace-lounge.jpg'


const diningData = [
  {
    "id": 1,
    "title": "Cozy Corner",
    "image": kormangala,
    "description": "Nestled in the heart of Koramangala, The Cozy Corner offers a delightful escape from the bustling city life. As you walk in, you’re greeted by soft, ambient lighting and comfortable seating that invites you to relax and unwind. The restaurant is designed with plush cushions and warm tones, making it perfect for a romantic dinner or a casual outing with friends. The menu features a mix of classic and contemporary dishes, catering to a variety of tastes.",
    "rating": 4.2,
    "price": 700,
    "location": "Bangalore",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "The Cozy Corner",
    "discount": "10% OFF",
    "reviews": 850,
    "prepTime": 20,
    "tags": ["casual", "romantic"],
    "portionSize": "2 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "Multi-cuisine",
    "userRatings": [
      { "user": "Amit", "comment": "Great ambiance, loved the food!", "rating": 4.5 },
      { "user": "Nisha", "comment": "Service was a bit slow but overall good.", "rating": 4.0 },
      { "user": "Vikram", "comment": "Comfortable seating and decent pricing.", "rating": 4.2 },
      { "user": "Riya", "comment": "Nice place for a quiet dinner.", "rating": 4.3 }
    ]
  },
  {
    "id": 2,
    "title": "Urban Loft",
    "image": bandra,
    "description": "If you're looking for a dining experience that combines urban flair with contemporary style, Urban Loft Cafe in Bandra is the place to be. The restaurant’s industrial decor—featuring exposed brick walls, steel beams, and stylish furniture—creates a chic and modern atmosphere that’s perfect for casual outings or Instagram-worthy moments.",
    "rating": 4.5,
    "price": 900,
    "location": "Mumbai",
    "deliveryTime": 35,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Urban Loft Cafe",
    "discount": "Flat ₹100 OFF",
    "reviews": 1200,
    "prepTime": 25,
    "tags": ["casual", "instagrammable"],
    "portionSize": "2 people",
    "openTimings": "12:00 PM - 12:00 AM",
    "cuisine": "Continental & Fusion",
    "userRatings": [
      { "user": "Rahul", "comment": "Perfect spot for friends and great coffee.", "rating": 4.7 },
      { "user": "Pooja", "comment": "Loved the vibes and presentation.", "rating": 4.6 },
      { "user": "Tanvi", "comment": "Music was a bit loud but food was excellent.", "rating": 4.3 },
      { "user": "Sameer", "comment": "Nice interiors and fast service.", "rating": 4.5 }
    ]
  },
  {
    "id": 3,
    "title": "Sunlit Patio",
    "image": caunaught,
    "description": "Located in the vibrant Connaught Place, Patio Delight offers a bright and airy dining experience perfect for both family outings and daytime meet-ups. With large windows allowing natural sunlight to flood the space, the atmosphere is light, refreshing, and comfortable.",
    "rating": 4.3,
    "price": 650,
    "location": "Delhi ",
    "deliveryTime": 28,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts"],
    "restaurantName": "Patio Delight",
    "discount": "No discount",
    "reviews": 950,
    "prepTime": 22,
    "tags": ["family", "day‑time"],
    "portionSize": "2 people",
    "openTimings": "10:00 AM - 10:00 PM",
    "cuisine": "North Indian & Snacks",
     "userRatings": [
      { "user": "Sahil", "comment": "Sunlight and food combo was amazing!", "rating": 4.3 },
      { "user": "Divya", "comment": "Perfect for lunch with family.", "rating": 4.2 },
      { "user": "Manoj", "comment": "Nice ambiance but limited menu.", "rating": 4.0 },
      { "user": "Nikita", "comment": "Fresh food and courteous staff.", "rating": 4.4 }
    ]
  },
  {
    "id": 4,
    "title": "Vintage Vault",
    "image": mgRoad,
    "description": "The Vintage Vault is a fine-dining experience with a retro twist. The moment you step inside, you are transported back in time, with bold red walls and an array of elegant antiques setting the tone for a classy yet nostalgic atmosphere. The restaurant's attention to detail is impressive, with every corner showcasing vintage décor that beautifully complements the high-end, sophisticated dining experience.",
    "rating": 4.7,
    "price": 1200,
    "location": "Bangalore",
    "deliveryTime": 40,
    "category": "Dining",
    "availability": false,
    "allergens": ["dairy"],
    "restaurantName": "The Vintage Vault",
    "discount": "20% OFF",
    "reviews": 1100,
    "prepTime": 35,
    "tags": ["fine‑dining", "romantic"],
    "portionSize": "2 people",
    "openTimings": "6:00 PM - 1:00 AM",
    "cuisine": "European",
    "userRatings": [
      { "user": "Arjun", "comment": "Luxury dining at its best.", "rating": 4.8 },
      { "user": "Sneha", "comment": "Loved the old-school vibes.", "rating": 4.6 },
      { "user": "Neeraj", "comment": "Bit expensive but worth it.", "rating": 4.7 },
      { "user": "Anjali", "comment": "Amazing desserts and ambiance.", "rating": 4.9 }
    ]
  },
  {
    "id": 5,
    "title": "Modern Terrace",
    "image": jayanagar,
    "description": "Perched on a rooftop in Jayanagar, Skyline Terrace offers a modern, open-air dining experience with stunning views of the city skyline. The contemporary terrace seating provides the perfect setting for a relaxed evening meal, where you can enjoy the cool breeze while indulging in some great food.",
    "rating": 4.4,
    "price": 1000,
    "location": "Bangalore",
    "deliveryTime": 38,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Skyline Terrace",
    "discount": "Flat ₹150 OFF",
    "reviews": 780,
    "prepTime": 30,
    "tags": ["casual", "outdoor"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "Modern Indian & Grill",
    "userRatings": [
      { "user": "Karan", "comment": "Great rooftop views, perfect for evenings.", "rating": 4.4 },
      { "user": "Megha", "comment": "Food was delicious, ambiance top-notch.", "rating": 4.5 },
      { "user": "Rohit", "comment": "Loved the lighting and seating.", "rating": 4.3 },
      { "user": "Sanya", "comment": "Relaxing place, ideal for weekends.", "rating": 4.6 }
    ]
  },
  {
    "id": 6,
    "title": "Wood & Warmth",
    "image": indranagar,
    "description": "Tucked away in the trendy neighborhood of Indiranagar, Wood & Warmth brings the charm of rustic wooden interiors and a cozy, intimate atmosphere. This dining spot is perfect for those seeking a comforting experience, with its warm, ambient lighting and rich wooden furnishings creating an inviting space.",
    "rating": 4.1,
    "price": 550,
    "location": "Bangalore",
    "deliveryTime": 32,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Wood & Warmth",
    "discount": "5% OFF",
    "reviews": 640,
    "prepTime": 20,
    "tags": ["casual", "family"],
    "portionSize": "2 people",
    "openTimings": "12:00 PM - 10:00 PM",
    "cuisine": "Indian & Comfort Food",
    "userRatings": [
      { "user": "Ankit", "comment": "Wooden interiors are so relaxing!", "rating": 4.2 },
      { "user": "Neha", "comment": "Perfect for chill family dinners.", "rating": 4.0 },
      { "user": "Ishaan", "comment": "Affordable and cozy spot.", "rating": 4.3 },
      { "user": "Radhika", "comment": "Comfort food at its best!", "rating": 4.1 }
    ]
  },
  {
    "id": 7,
    "title": "Minimalist Space",
    "image": hauz,
    "description": "Located in the vibrant area of Hauz Khas, Yellow Loft is a minimalist’s dream come true. The restaurant exudes a calm and clean aesthetic with its striking yellow seating, white walls, and modern, minimalist décor. The space is bright and airy, offering a peaceful escape from the city’s hustle and bustle. Yellow Loft’s focus is on simplicity, which is reflected not only in the décor but also in the approach to food.",
    "rating": 4.3,
    "price": 600,
    "location": "Delhi",
    "deliveryTime": 27,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Yellow Loft",
    "discount": "No discount",
    "reviews": 520,
    "prepTime": 18,
    "tags": ["casual", "trendy"],
    "portionSize": "2 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "Modern European",
    "userRatings": [
      { "user": "Arnav", "comment": "Love the clean and calm setup.", "rating": 4.3 },
      { "user": "Maya", "comment": "Minimalist design feels so peaceful.", "rating": 4.4 },
      { "user": "Zoya", "comment": "Great for solo working lunches.", "rating": 4.2 },
      { "user": "Dev", "comment": "Food is simple yet flavorful.", "rating": 4.3 }
    ]
  },
  {
    "id": 8,
    "title": "Green Nook",
    "image": bandraWest,
    "description": "The Green Nook is a hidden gem in the heart of Bandra West, offering a serene escape amidst vibrant green accents and cozy corners. The eco-friendly design is at the forefront, with lush greenery and recycled materials used throughout the space. The restaurant’s laid-back atmosphere, paired with its warm yet vibrant décor, creates the perfect setting for small gatherings, whether it’s with friends, family, or colleagues.",
    "rating": 4.6,
    "price": 800,
    "location": "Mumbai",
    "deliveryTime": 29,
    "category": "Dining",
    "availability": false,
    "allergens": ["nuts", "dairy"],
    "restaurantName": "The Green Nook",
    "discount": "15% OFF",
    "reviews": 890,
    "prepTime": 24,
    "tags": ["casual", "eco‑friendly"],
    "portionSize": "2 people",
    "openTimings": "10:00 AM - 10:00 PM",
    "cuisine": "Organic & Healthy",
    "userRatings": [
      { "user": "Rishi", "comment": "Eco-friendly vibes are awesome!", "rating": 4.6 },
      { "user": "Trisha", "comment": "Loved the greenery and food quality.", "rating": 4.7 },
      { "user": "Harshita", "comment": "Perfect for mindful eating.", "rating": 4.5 },
      { "user": "Kabir", "comment": "Calm place with healthy options.", "rating": 4.6 }
    ]
  },
  {
    "id": 9,
    "title": "Bright Bistro",
    "image": panaji,
    "description": "Situated in the picturesque city of Panaji, Sunny Bistro captures the essence of bright, sun-drenched spaces with its charming wooden furnishings and cheerful atmosphere. The restaurant is designed to be a welcoming space for all, offering an inviting ambiance that feels light and airy. With large windows that let in plenty of natural light, the bistro offers the perfect setting for a daytime meal",
    "rating": 4.2,
    "price": 680,
    "location": "Goa",
    "deliveryTime": 45,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Sunny Bistro",
    "discount": "No discount",
    "reviews": 430,
    "prepTime": 28,
    "tags": ["casual", "day‑time"],
    "portionSize": "2 people",
    "openTimings": "9:00 AM - 9:00 PM",
    "cuisine": "Goan & Café-style",
    "userRatings": [
      { "user": "Nakul", "comment": "So bright and cheerful inside!", "rating": 4.3 },
      { "user": "Preeti", "comment": "Goan dishes were authentic!", "rating": 4.4 },
      { "user": "Aanya", "comment": "Loved sitting near the windows.", "rating": 4.2 },
      { "user": "Varun", "comment": "Perfect spot for brunch!", "rating": 4.1 }
    ]
  },
  {
    "id": 10,
    "title": "Elegant Hall",
    "image": caunaught,
    "description": "Grand Hall is a true epitome of luxury dining, offering an elegant atmosphere paired with impeccable service and a refined menu. Located in the heart of Connaught Place, this restaurant boasts a spacious interior with classic décor, polished wooden floors, and plush seating arrangements. The atmosphere is quiet yet majestic, perfect for both intimate dinners and grand celebrations",
    "rating": 4.8,
    "price": 1400,
    "location": "Delhi",
    "deliveryTime": 33,
    "category": "Dining",
    "availability": true,
    "allergens": ["dairy", "nuts"],
    "restaurantName": "Grand Hall",
    "discount": "20% OFF",
    "reviews": 2300,
    "prepTime": 35,
    "tags": ["fine‑dining", "luxury"],
    "portionSize": "4 people",
    "openTimings": "6:00 PM - 1:00 AM",
    "cuisine": "Gourmet Indian & Continental",
    "userRatings": [
      { "user": "Meera", "comment": "Truly elegant dining experience.", "rating": 4.9 },
      { "user": "Saurabh", "comment": "Staff is extremely professional.", "rating": 4.8 },
      { "user": "Diya", "comment": "Perfect for special occasions.", "rating": 4.9 },
      { "user": "Jatin", "comment": "Top-notch presentation and taste.", "rating": 4.7 }
    ]
  },
  {
    "id": 11,
    "title": "Urban Greenery",
    "image": greenLounge,
    "description": "Indoor garden touches with leafy decoration and soft lighting.",
    "rating": 4.0,
    "price": 750,
    "location": "Indore",
    "deliveryTime": 25,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Green Lounge",
    "discount": "5% OFF",
    "reviews": 390,
    "prepTime": 22,
    "tags": ["casual", "eco‑friendly"],
    "portionSize": "2 people",
    "openTimings": "10:00 AM - 10:00 PM",
    "cuisine": "Vegetarian & Organic",
    "userRatings": [
      { "user": "Simran", "comment": "Feels like dining in a garden!", "rating": 4.1 },
      { "user": "Naveen", "comment": "Lovely ambiance with green touches.", "rating": 4.0 },
      { "user": "Megha", "comment": "Healthy food options and peaceful vibes.", "rating": 4.2 },
      { "user": "Rajeev", "comment": "Good for vegetarian meals.", "rating": 3.9 }
    ]
  },
  {
    "id": 12,
    "title": "Lofty Vibes",
    "image": juhu,
    "description": "High ceilings and airy layout with loft-style décor.",
    "rating": 4.5,
    "price": 850,
    "location": "Mumbai",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Lofty Vibes",
    "discount": "Flat ₹80 OFF",
    "reviews": 670,
    "prepTime": 25,
    "tags": ["casual", "trendy"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 12:00 AM",
    "cuisine": "Global Fusion",
    "userRatings": [
      { "user": "Akshay", "comment": "Cool loft-style space!", "rating": 4.5 },
      { "user": "Pooja", "comment": "Loved the food and open layout.", "rating": 4.6 },
      { "user": "Jatin", "comment": "Spacious and lively place.", "rating": 4.4 },
      { "user": "Ritika", "comment": "Perfect for group dinners.", "rating": 4.5 }
    ]
  },
  {
    "id": 13,
    "title": "Rustic Charm",
    "image": vasant,
    "description": "Cozy rustic accents mixed with modern comfort seating.",
    "rating": 4.3,
    "price": 580,
    "location": "Delhi",
    "deliveryTime": 29,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts"],
    "restaurantName": "Rustic Charm Bistro",
    "discount": "No discount",
    "reviews": 510,
    "prepTime": 20,
    "tags": ["casual", "family"],
    "portionSize": "2 people",
    "openTimings": "12:00 PM - 11:00 PM",
    "cuisine": "Indian & Continental",
    "userRatings": [
      { "user": "Tanya", "comment": "Rustic interiors are super cozy.", "rating": 4.3 },
      { "user": "Devansh", "comment": "Tried their Indian thali – delicious!", "rating": 4.2 },
      { "user": "Kavya", "comment": "Calm environment, great service.", "rating": 4.4 },
      { "user": "Aditya", "comment": "Small but charming place.", "rating": 4.3 }
    ]
  },
  {
    "id": 14,
    "title": "Chic Haven",
    "image": chicHeaven,
    "description": "Bold red interiors paired with modern furniture for chic vibes.",
    "rating": 4.6,
    "price": 950,
    "location": "Delhi",
    "deliveryTime": 31,
    "category": "Dining",
    "availability": false,
    "allergens": ["dairy"],
    "restaurantName": "Chic Haven",
    "discount": "15% OFF",
    "reviews": 880,
    "prepTime": 27,
    "tags": ["fine‑dining", "trendy"],
    "portionSize": "2 people",
    "openTimings": "1:00 PM - 11:00 PM",
    "cuisine": "Modern Indian",
    "userRatings": [
      { "user": "Ishita", "comment": "Very classy place, loved the interiors!", "rating": 4.7 },
      { "user": "Rohan", "comment": "Modern menu and great cocktails.", "rating": 4.6 },
      { "user": "Diya", "comment": "Ideal for a date night!", "rating": 4.8 },
      { "user": "Yash", "comment": "Bit pricey but totally worth it.", "rating": 4.5 }
    ]
  },
  {
    "id": 15,
    "title": "Bright Atrium",
    "image": atriumDining,
    "description": "Open atrium-style seating with natural light and spacious layout.",
    "rating": 4.4,
    "price": 800,
    "location": "Goa",
    "deliveryTime": 45,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Atrium Dining",
    "discount": "No discount",
    "reviews": 720,
    "prepTime": 30,
    "tags": ["casual", "day‑time"],
    "portionSize": "3 people",
    "openTimings": "10:00 AM - 10:00 PM",
    "cuisine": "Goan & Seafood",
       "userRatings": [
      { "user": "Sneha", "comment": "Love the sunlight and open space!", "rating": 4.4 },
      { "user": "Rajat", "comment": "Perfect spot for brunches.", "rating": 4.3 },
      { "user": "Anaya", "comment": "Goan seafood was fresh and tasty.", "rating": 4.5 },
      { "user": "Harsh", "comment": "Bright and spacious, feels great.", "rating": 4.4 }
    ]
  },
  {
    "id": 16,
    "title": "Elegant Corridor",
    "image": parkStreet,
    "description": "Long corridor-style seating with luxurious accents.",
    "rating": 4.7,
    "price": 1300,
    "location": "Kolkata",
    "deliveryTime": 34,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts", "dairy"],
    "restaurantName": "Corridor Elegance",
    "discount": "20% OFF",
    "reviews": 1500,
    "prepTime": 33,
    "tags": ["fine‑dining", "luxury"],
    "portionSize": "4 people",
    "openTimings": "6:00 PM - 1:00 AM",
    "cuisine": "French & Continental",
    "userRatings": [
      { "user": "Anjali", "comment": "Amazing fine dining experience!", "rating": 4.8 },
      { "user": "Sourav", "comment": "Loved the French cuisine.", "rating": 4.7 },
      { "user": "Meena", "comment": "Great ambiance and service.", "rating": 4.6 },
      { "user": "Arjun", "comment": "Perfect place for celebrations.", "rating": 4.7 }
    ]
  },
  {
    "id": 17,
    "title": "Checkerboard Cafe",
    "image": retroCheck,
    "description": "Retro checkerboard floor with colorful modern seating.",
    "rating": 4.2,
    "price": 620,
    "location": "Noida",
    "deliveryTime": 26,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Retro Check",
    "discount": "Flat ₹50 OFF",
    "reviews": 460,
    "prepTime": 20,
    "tags": ["casual", "retro"],
    "portionSize": "2 people",
    "openTimings": "10:00 AM - 10:00 PM",
    "cuisine": "Cafe & Snacks",
     "userRatings": [
      { "user": "Nikhil", "comment": "Great retro vibes and snacks!", "rating": 4.3 },
      { "user": "Richa", "comment": "Cozy and colorful place.", "rating": 4.1 },
      { "user": "Vikram", "comment": "Perfect for quick bites.", "rating": 4.2 },
      { "user": "Sneha", "comment": "Friendly staff and tasty food.", "rating": 4.0 }
    ]
  },
  {
    "id": 18,
    "title": "Warm Lounge",
    "image":tNagar,
    "description": "Vibrant green walls and soft lounge seating for relaxed meals.",
    "rating": 4.5,
    "price": 880,
    "location": "Chennai",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Green Lounge",
    "discount": "No discount",
    "reviews": 590,
    "prepTime": 24,
    "tags": ["casual", "family"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "South Indian & Continental",
    "userRatings": [
      { "user": "Karthik", "comment": "Lovely family spot!", "rating": 4.5 },
      { "user": "Priya", "comment": "Good food and comfy seating.", "rating": 4.4 },
      { "user": "Ashwin", "comment": "Nice ambiance for relaxed meals.", "rating": 4.6 },
      { "user": "Divya", "comment": "Friendly staff and clean place.", "rating": 4.5 }
    ]
  },
  {
    "id": 19,
    "title": "Sunbeam Dining",
    "image": dwarka,
    "description": "Wood‑rich décor bathed in natural sunlight during the day.",
    "rating": 4.3,
    "price": 700,
    "location": "Delhi",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": false,
    "allergens": [],
    "restaurantName": "Sunbeam Dining",
    "discount": "10% OFF",
    "reviews": 680,
    "prepTime": 28,
    "tags": ["casual", "day‑time"],
    "portionSize": "2 people",
    "openTimings": "9:00 AM - 9:00 PM",
    "cuisine": "Healthy & Organic",
    "userRatings": [
      { "user": "Manish", "comment": "Beautiful natural light inside.", "rating": 4.2 },
      { "user": "Alka", "comment": "Great healthy food options.", "rating": 4.4 },
      { "user": "Sonal", "comment": "Nice place for day meals.", "rating": 4.3 },
      { "user": "Ravi", "comment": "Warm and welcoming atmosphere.", "rating": 4.1 }
    ]
  },
  {
    "id": 20,
    "title": "Classic Elegance",
    "image": southExtension,
    "description": "Timeless décor with classic furniture and soft lighting.",
    "rating": 4.8,
    "price": 1450,
    "location": "Chennai",
    "deliveryTime": 36,
    "category": "Dining",
    "availability": true,
    "allergens": ["dairy"],
    "restaurantName": "Classic Grace",
    "discount": "Flat ₹200 OFF",
    "reviews": 2100,
    "prepTime": 35,
    "tags": ["fine‑dining", "luxury"],
    "portionSize": "4 people",
    "openTimings": "6:00 PM - 12:00 AM",
    "cuisine": "Italian & Continental",
    "userRatings": [
      { "user": "Vineet", "comment": "Luxury dining at its best!", "rating": 4.9 },
      { "user": "Neha", "comment": "Elegant and classy place.", "rating": 4.8 },
      { "user": "Amit", "comment": "Perfect for special occasions.", "rating": 4.7 },
      { "user": "Shreya", "comment": "Great service and food quality.", "rating": 4.8 }
    ]
  },
  {
    "id": 21,
    "title": "Glasshouse Cafe",
    "image": saltLake,
    "description": "Bright glass‑enclosed seating offering soothing outdoor views.",
    "rating": 4.1,
    "price": 780,
    "location": "Kolkata",
    "deliveryTime": 28,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Glasshouse Cafe",
    "discount": "No discount",
    "reviews": 520,
    "prepTime": 23,
    "tags": ["casual", "day‑time"],
    "portionSize": "2 people",
    "openTimings": "9:00 AM - 9:00 PM",
    "cuisine": "Cafe & Continental"
  },
  {
    "id": 22,
    "title": "Loft & Lights",
    "image": vile,
    "description": "Lofty ceiling and hanging fixtures give this place a modern flair.",
    "rating": 4.5,
    "price": 920,
    "location": "Mumbai",
    "deliveryTime": 29,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts"],
    "restaurantName": "Loft & Lights",
    "discount": "10% OFF",
    "reviews": 750,
    "prepTime": 25,
    "tags": ["casual", "trendy"],
    "portionSize": "3 people",
    "openTimings": "12:00 PM - 12:00 AM",
    "cuisine": "Modern Indian & Fusion"
  },
  {
    "id": 23,
    "title": "Rustic Terrace",
    "image": sector14,
    "description": "Rustic elements along with terrace seating overlooking greenery.",
    "rating": 4.3,
    "price": 800,
    "location": "Gurgaon",
    "deliveryTime": 27,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Terrace Rustic",
    "discount": "Flat ₹70 OFF",
    "reviews": 600,
    "prepTime": 22,
    "tags": ["casual", "outdoor"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 10:00 PM",
    "cuisine": "Continental & Barbecue"
  },
  {
    "id": 24,
    "title": "Red Wall Lounge",
    "image": redWallLounge,
    "description": "Bold red décor with comfortable lounge seating for relaxing meals.",
    "rating": 4.6,
    "price": 950,
    "location": "Gurgaon",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": false,
    "allergens": ["dairy"],
    "restaurantName": "Red Wall Lounge",
    "discount": "No discount",
    "reviews": 880,
    "prepTime": 27,
    "tags": ["casual", "lounge"],
    "portionSize": "2 people",
    "openTimings": "1:00 PM - 11:00 PM",
    "cuisine": "Lounge & Fusion"
  },
  {
    "id": 25,
    "title": "Terrace Atrium",
    "image": andheriWest,
    "description": "Atrium style with partially open roof for an alfresco feel.",
    "rating": 4.4,
    "price": 830,
    "location": "Mumbai",
    "deliveryTime": 32,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Atrium Terrace",
    "discount": "5% OFF",
    "reviews": 670,
    "prepTime": 26,
    "tags": ["casual", "outdoor"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "Mediterranean & Asian"
  },
  {
    "id": 26,
    "title": "Luxe Corridor",
    "image": banjaraHills,
    "description": "Luxury lounge with elegant corridor-style seating setup.",
    "rating": 4.7,
    "price": 1350,
    "location": "Hyderabad",
    "deliveryTime": 36,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts", "dairy"],
    "restaurantName": "Corridor Luxe",
    "discount": "15% OFF",
    "reviews": 1450,
    "prepTime": 33,
    "tags": ["fine‑dining", "luxury"],
    "portionSize": "4 people",
    "openTimings": "6:00 PM - 1:00 AM",
    "cuisine": "French & Continental"
  },
  {
    "id": 27,
    "title": "Checkered Cafe",
    "image":checkeredCafe,
    "description": "Playful checkered flooring with bright seating and casual vibes.",
    "rating": 4.2,
    "price": 640,
    "location": "Delhi",
    "deliveryTime": 28,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Checkered Cafe",
    "discount": "Flat ₹60 OFF",
    "reviews": 540,
    "prepTime": 21,
    "tags": ["casual", "retro"],
    "portionSize": "2 people",
    "openTimings": "10:00 AM - 10:00 PM",
    "cuisine": "Cafe & Fast Food"
  },
  {
    "id": 28,
    "title": "Orange & Green",
    "image": chandniChowk,
    "description": "Fresh color palette with orange tables and green walls adorned.",
    "rating": 4.5,
    "price": 870,
    "location": "Delhi",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts"],
    "restaurantName": "Color Pop",
    "discount": "10% OFF",
    "reviews": 680,
    "prepTime": 24,
    "tags": ["casual", "vibrant"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "Healthy & Vegan"
  },
  {
    "id": 29,
    "title": "Wooden Terrace",
    "image": annaNagar,
    "description": "All-wood décor with terrace seating offering natural charm.",
    "rating": 4.3,
    "price": 720,
    "location": "Chennai",
    "deliveryTime": 29,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Woodland Terrace",
    "discount": "No discount",
    "reviews": 580,
    "prepTime": 26,
    "tags": ["casual", "outdoor"],
    "portionSize": "3 people",
    "openTimings": "9:00 AM - 9:00 PM",
    "cuisine": "Continental & Grill"
  },
  {
    "id": 30,
    "title": "Classic Wooden",
    "image": classicWood,
    "description": "Elegant wooden furniture paired with classic décor elements.",
    "rating": 4.8,
    "price": 1420,
    "location": "Chennai",
    "deliveryTime": 34,
    "category": "Dining",
    "availability": true,
    "allergens": ["dairy"],
    "restaurantName": "Classic Wood",
    "discount": "Flat ₹180 OFF",
    "reviews": 2000,
    "prepTime": 34,
    "tags": ["fine‑dining", "luxury"],
    "portionSize": "4 people",
    "openTimings": "6:00 PM - 12:00 AM",
    "cuisine": "Italian & European"
  },
  {
    "id": 31,
    "title": "Garden Atrium",
    "image": gardenAtrium,
    "description": "Garden-style atrium to give an outdoor dining feel indoors.",
    "rating": 4.0,
    "price": 800,
    "location": "Delhi",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Garden Atrium",
    "discount": "No discount",
    "reviews": 480,
    "prepTime": 25,
    "tags": ["casual", "outdoor"],
    "portionSize": "3 people",
    "openTimings": "9:00 AM - 10:00 PM",
    "cuisine": "Healthy & Organic"
  },
  {
    "id": 32,
    "title": "Lofty Retreat",
    "image":loftyRetreat,
    "description": "High rise style with loft seating and ambient lighting.",
    "rating": 4.5,
    "price": 920,
    "location": "Delhi",
    "deliveryTime": 31,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts"],
    "restaurantName": "Lofty Retreat",
    "discount": "15% OFF",
    "reviews": 710,
    "prepTime": 26,
    "tags": ["casual", "trendy"],
    "portionSize": "3 people",
    "openTimings": "12:00 PM - 12:00 AM",
    "cuisine": "Modern Indian",

  },
  {
    "id": 33,
    "title": "Rustic Glow",
    "image": rusticGlowLounge,
    "description": "Warm rustic glow with communal seating and soft lighting.",
    "rating": 4.3,
    "price": 800,
    "location": "Delhi",
    "deliveryTime": 29,
    "category": "Dining",
    "availability": false,
    "allergens": ["dairy"],
    "restaurantName": "Rustic Glow Lounge",
    "discount": "No discount",
    "reviews": 650,
    "prepTime": 23,
    "tags": ["casual", "communal"],
    "portionSize": "3 people",
    "openTimings": "1:00 PM - 11:00 PM",
    "cuisine": "European & Bistro",

  },
  {
    "id": 34,
    "title": "Red Retro",
    "image": redRetroLounge,
    "description": "Retro red walls give this place a bold character.",
    "rating": 4.6,
    "price": 980,
    "location": "Mumbai",
    "deliveryTime": 33,
    "category": "Dining",
    "availability": true,
    "allergens": ["nuts"],
    "restaurantName": "Red Retro Lounge",
    "discount": "10% OFF",
    "reviews": 820,
    "prepTime": 28,
    "tags": ["casual", "retro"],
    "portionSize": "2 people",
    "openTimings": "12:00 PM - 12:00 AM",
    "cuisine": "American Diner"
  },
  {
    "id": 35,
    "title": "Terrace Lounge",
    "image": terraceLounge,
    "description": "Terrace-style lounge with comfortable seating and skyline views.",
    "rating": 4.4,
    "price": 860,
    "location": "Bangalore",
    "deliveryTime": 30,
    "category": "Dining",
    "availability": true,
    "allergens": [],
    "restaurantName": "Terrace Lounge",
    "discount": "5% OFF",
    "reviews": 720,
    "prepTime": 26,
    "tags": ["casual", "outdoor"],
    "portionSize": "3 people",
    "openTimings": "11:00 AM - 11:00 PM",
    "cuisine": "Asian Fusion"
  }
]

export default diningData